--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/GrapplingHook
build-by-default: true
branches:
- PM4
projects:
  GrapplingHook:
    path: ""
    icon: icon-grapplinghook.png
    lint:
      phpstan: false
...
