#    ____                                  _   _                   _   _                   _    
#  / ___|  _ __    __ _   _ __    _ __   | | (_)  _ __     __ _  | | | |   ___     ___   | | __
# | |  _  | '__|  / _` | | '_ \  | '_ \  | | | | | '_ \   / _` | | |_| |  / _ \   / _ \  | |/ /
# | |_| | | |    | (_| | | |_) | | |_) | | | | | | | | | | (_| | |  _  | | (_) | | (_) | |   < 
#  \____| |_|     \__,_| | .__/  | .__/  |_| |_| |_| |_|  \__, | |_| |_|  \___/   \___/  |_|\_\
#                        |_|     |_|                      |___/                                
#           by fernanACM and korado531m7
# The best hook to play Spider-Man, only in PocketMine-MP 5.0!. Updated by fernanACM

# DO NOT TOUCH
config-version: "1.0.0"

# Prefix plugin
Prefix: "&l&f[&bGrapplingHook&f]&8»&r "

# DATABASE
database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: database/GrapplingHook.db
  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    schema: your_schema
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1

# Item from GrapplingHook
GrapplingHook:
  # Item name
  name: 
    - "&r&l&aGrapplingHook"
    - "&r&7[RIGHT CLICK]"
  # Lore for the item
  lore:
    - "&r&bHave fun playing Spider-Man"
    - "&r&aby: &ffernanACM"
  # Cooldown
  cooldown: 5

# TIME MODE
TimeMode:
  years: "{YEAR} year(s)"
  months: "{MONTH} month(s)"
  days: "{DAY} day(s)"
  hours: "{HOUR} hour(s)"
  minutes: "{MINUTE} minute(s)"
  seconds: "{SECOND} second(s)"

# MESSAGES
Messages:
  no-permission: "&cYou don't have permissions for this!"
  not-numeric: "&cIt is not numeric!"
  full-inventory: "&cYour inventory is full!"
  received successfully: "&aYou have successfully received your &bGrapplingHook"
  you-have-cooldown: "&cCooldown:&b {COOLDOWN}"